config/routes.rb
BookingApp::Application.routes.draw do
  

  root :to => "rezerwacjas#index"
  resources :roles

  devise_for :users
  resources :users
  match 'przystanki' => "przystaneks#index", :as => 'przystaneks_index'
  match 'przystanek/nowy' => "przystaneks#new", :as => 'new_przystanek'
  match 'przystanek/create' => "przystaneks#create", :as => 'przystaneks'
  match 'przystanek/:id/edytuj' => "przystaneks#edit", :as => 'przystanek_edytuj'
  match 'przystanek/:id' => 'przystaneks#show', :as => 'przystanek_pokaz' 
  match 'przystanek/:id/usun' => 'przystaneks#destroy', :as => 'usun_przystanek'
  match 'wycieczki' => "wycieczkas#index", :as => 'wycieczkas_index'
  match 'wycieczka/nowa' => "wycieczkas#new", :as => 'new_wycieczka'
  match 'wycieczka/create' => "wycieczkas#create", :as => 'wycieczkas'
  match 'wycieczka/:id/lista' => "wycieczkas#lista", :as => 'lista_rezerwacji'
  match 'wycieczka/:id' => 'wycieczkas#show', :as => 'wycieczka_pokaz'
  match 'wycieczka/:id/edytuj' => 'wycieczkas#edit', :as => 'edit_wycieczka'
  match 'wycieczka/:id/usun' => 'wycieczkas#destroy', :as => 'usun_wycieczka'

  match 'rezerwacje' => "rezerwacjas#index", :as => 'rezerwacjas_index'
  match 'rezerwacja/nowa' => "rezerwacjas#new", :as => 'new_rezerwacja'
  match 'rezerwacja/create' => "rezerwacjas#create", :as => 'rezerwacjas'
  match 'rezerwacja/wycieczka/:id' => "rezerwacjas#new_const", :as => 'dodatkowa_rezerwacja'
  match 'rezerwacja/:id/nowa/osoba' => "rezerwacjas#new_person", :as => 'nowa_osoba'
  match 'rezerwacja/:id' => "rezerwacjas#show", :as => 'rezerwacja_pokaz'
  match 'rezerwacja/:id/edytuj' => "rezerwacjas#edit", :as => 'rezerwacja_edytuj'
  
  devise_scope :user do get "/wyloguj" => "devise/sessions#destroy" end
  devise_scope :user do get "/zaloguj" => "devise/sessions#new" ,:as => 'zaloguj' end
  match "/zarejestruj" => "users#new" ,:as => 'zarejestruj' 
  resources :wycieczkas

  resources :przystaneks

  resources :rezerwacjas

end

app/models/wycieczka.rb
class Wycieczka < ActiveRecord::Base
  attr_accessible :wycieczka_id,:data, :nazwa, :updated_by
  validates_presence_of :data, on: :create, message: "Uzupelnij date"
  validates_presence_of :nazwa, on: :create, message: "Wpisz nazwe wycieczki"
def combined_value
  "#{self.nazwa} #{self.data.strftime("%d.%m.%Y")} r."
end

end

app/controllers/wycieczkas_controller.rb
class WycieczkasController < ApplicationController
  # GET /wycieczkas
  # GET /wycieczkas.json
  authorize_resource
  before_filter :authenticate_user!
  def index
    @wycieczkas = Wycieczka.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wycieczkas }
    end
  end

  def lista 
    @nazwa = Wycieczka.find_by_id(params[:id]).nazwa
    @rezerwacjas = Rezerwacja.find(:all, :conditions => {:nazwa => params[:id]})
    respond_to do |format|
      format.html # lista.html.erb
      format.json { render json: @rezerwacjas }
      format.xls { response.headers['Content-Disposition'] = 'attachment; filename="' + Wycieczka.find_by_id(params[:id]).combined_value + '.xls"'}
    end
  end
  # GET /wycieczkas/1
  # GET /wycieczkas/1.json
  def show
    @wycieczka = Wycieczka.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wycieczka }
    end
  end

  # GET /wycieczkas/new
  # GET /wycieczkas/new.json
  def new
    @wycieczka = Wycieczka.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wycieczka }
    end
  end

  # GET /wycieczkas/1/edit
  def edit
    @wycieczka = Wycieczka.find(params[:id])
  end

  # POST /wycieczkas
  # POST /wycieczkas.json
  def create
    @wycieczka = Wycieczka.new(params[:wycieczka])

    respond_to do |format|
      if @wycieczka.save
        format.html { redirect_to @wycieczka, notice: 'Wycieczka was successfully created.' }
        format.json { render json: @wycieczka, status: :created, location: @wycieczka }
      else
        format.html { render action: "new" }
        format.json { render json: @wycieczka.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wycieczkas/1
  # PUT /wycieczkas/1.json
  def update
    @wycieczka = Wycieczka.find(params[:id])

    respond_to do |format|
      if @wycieczka.update_attributes(params[:wycieczka])
        format.html { redirect_to @wycieczka, notice: 'Wycieczka was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wycieczka.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wycieczkas/1
  # DELETE /wycieczkas/1.json
  def destroy
    @wycieczka = Wycieczka.find(params[:id])
    @wycieczka.destroy

    respond_to do |format|
      format.html { redirect_to wycieczkas_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/wycieczkas_helper.rb
module WycieczkasHelper
end

app/views/wycieczkas/_form.html.erb
<div class="span3">
<%= simple_form_for @wycieczka, :html => { :class => 'form-inline' } do |f| %>

      <%= f.input :nazwa, collection: [ 'Praga','Praga Nocą','Skalne Miasto','Szwajcaria Saksońska', 'Drezno','Morawski Kras','Liberec', 'Wiedeń','Czeski Raj'], label: "Miejsce wycieczki", :prompt => "Wybierz miejsce wycieczki" %>
    
      <%= f.input :data, as: :string, :class => 'text_field' %>
      <%= f.input :updated_by, :as => :hidden, :input_html => { :value => current_user.id } %>

	</div>
	<div class="span12">
	<div class="form-actions">
    <%= f.submit "Dodaj", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                wycieczkas_index_path, :class => 'btn' %>
	</div>
<% end %>
</div>

app/views/wycieczkas/edit.html.erb
<%- model_class = Wycieczka -%>
<div class="span12">
<div class="page-header">
  <blockquote><p><big>Edytuj wycieczke numer: <%= params[:id] %>/<%= Wycieczka.find_by_id(params[:id]).created_at.year %></big></p></blockquote>
</div>
</div>
<%= render :partial => 'form' %>

app/views/wycieczkas/index.html.erb
    <%- model_class = Wycieczka -%>
<div class="span12">
<div class="page-header">
  <blockquote><p><big>Lista wycieczek</big></p></blockquote>
</div>
<table id="wycieczki" class="table table-striped">
  <thead>
    <tr>
    <th>Numer wycieczki</th>
    <th>Stworzona przez</th>
      <th><%= model_class.human_attribute_name(:nazwa) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @wycieczkas.each do |wycieczka| %>
      <tr>
        <td><%= link_to "#{wycieczka.id}/#{Wycieczka.find_by_id(wycieczka.id).created_at.year}", wycieczka_path(wycieczka) %></td>

        <td><%= User.find_by_id(wycieczka.updated_by).username %></td>
        <td><%= wycieczka.nazwa %></td>
        <td><%= wycieczka.data %></td>

        <td style="width:15%;">
          <%= link_to raw("<i class=\"icon-plus\"></i>"),
                      dodatkowa_rezerwacja_path(wycieczka), :class => 'btn btn-mini btn-primary', :title => "Dodaj rezerwacje",
                      :id => "add" %>
          <%= link_to raw("<i class=\"icon-list\"></i>"),
                      lista_rezerwacji_path(wycieczka), :class => 'btn btn-mini btn-warning', :title => "Lista wycieczki",
                      :id => "list" %>
          <%= link_to raw("<i class=\"icon-edit\"></i>"),
                      edit_wycieczka_path(wycieczka), :class => 'btn btn-mini btn-success', :title => "Edycja rezerwacji",
                      :id => "edit" %>
          <%= link_to raw("<i class=\"icon-remove\"></i>"),
                      usun_wycieczka_path(wycieczka),
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Jesteś pewien?')) },
                      :id => "delete",
                      :class => 'btn btn-mini btn-danger',
                      :title => "Usuń wycieczkę" %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to raw("<i class=\"icon-plus\"></i>  Dodaj nową wycieczkę"),
            new_wycieczka_path,
            :class => 'btn btn-primary' %>

</div>
 

app/views/wycieczkas/lista.html.erb
<div class="span12">
<%- model_class = Rezerwacja -%>
<div class="page-header">
   <blockquote><p><big>Lista uczestników wycieczki: <%= FindWycieczkaByID(params[:id]).humanize %></big></p> </blockquote>
</div>

<%= link_to raw("<i class=\"icon-download-alt\"></i> Pobierz do Excela"), lista_rezerwacji_path(format: "xls"), :class=>"btn btn-primary btn-success" %>
<br><br>
<table id="rezerwacje" class="table table-striped">
  <thead>
    <tr>
      <th>Numer rezerwacji</th>
      <th>Przystanek</th>
      <th><%= model_class.human_attribute_name(:imie) %></th>
      <th><%= model_class.human_attribute_name(:nazwisko) %></th>
      <th>Numer telefonu</th>
      <th>Data urodzenia</th>


      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rezerwacjas.each do |rezerwacja| %>

        <% if rezerwacja.zaplacona == 1 

        @class = "success"
      else
        @class = "error"
      end

     %>

 <tr class="<%= @class %>">
        <td><%= link_to "#{User.find_by_id(rezerwacja.updated_by).username[0..2]}/#{rezerwacja.id}/#{Rezerwacja.find_by_id(rezerwacja.id).created_at.year}", rezerwacja_pokaz_path(rezerwacja) %></td>
         <td><%= rezerwacja.przystaneks.first.nazwa %></td>
        <td><%= rezerwacja.imie %> </td>
        <td><%= rezerwacja.nazwisko %></td>
        <td><%= rezerwacja.nrtelefonu %></td>
        <td><%= rezerwacja.dataUrodzenia %></td>
        <td style="width:11%">
     <%= link_to raw("<i class=\"icon-plus\"></i>"),
                      nowa_osoba_path(rezerwacja), :class => 'btn btn-mini btn-primary', :title => "Dodaj rezerwacje",
                                                   :id => "add" %>
          <%= link_to raw("<i class=\"icon-list\"></i>"),
                        rezerwacja_pokaz_path(rezerwacja), :class => 'btn btn-mini btn-warning',  :title => "Pokaż rezerwacje" ,:id => "show" %>    
          <%= link_to raw("<i class=\"icon-edit\"></i>"),
                        rezerwacja_edytuj_path(rezerwacja), :class => 'btn btn-mini btn-success',  :title => "Edytuj rezerwacje", :id => "edit" %>         
          <%= link_to raw("<i class=\"icon-remove\"></i>"),
                      rezerwacja_path(rezerwacja),
                       :title => "Usuń rezerwacje",
                      :method => :delete,
                      :id => "delete",
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Jesteś pewien?')) },
                      :class => 'btn btn-mini btn-danger',
                      :title => "Usuń rezerwacje" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to raw("<i class=\"icon-plus\"></i> Dodaj nowego uczestnika"),
            dodatkowa_rezerwacja_path(params[:id]),
            :class => 'btn btn-primary' %>


</div>

app/views/wycieczkas/lista.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <LastAuthor>Aleksander Gładysz</LastAuthor>
  <LastPrinted>2013-06-25T23:30:58Z</LastPrinted>
  <Created>2013-06-25T21:23:42Z</Created>
  <Version>14.0</Version>
 </DocumentProperties>
 <OfficeDocumentSettings xmlns="urn:schemas-microsoft-com:office:office">
  <AllowPNG/>
 </OfficeDocumentSettings>
 <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">
  <WindowHeight>10900</WindowHeight>
  <WindowWidth>25480</WindowWidth>
  <!-- <WindowTopX>120</WindowTopX> -->
  <!-- <WindowTopY>140</WindowTopY> -->
  <ProtectStructure>False</ProtectStructure>
  <ProtectWindows>False</ProtectWindows>
 </ExcelWorkbook>
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="12" ss:Color="#000000"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="m706390908">
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Calibri" ss:Size="20" ss:Color="#000000" ss:Bold="1"/>
   <Interior ss:Color="#C0C0C0" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="s62">
   <Alignment ss:Vertical="Bottom" ss:WrapText="1"/>
  </Style>
  <Style ss:ID="s100">
   <Alignment ss:Vertical="Center"/>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="12" ss:Color="#000000"/>
  </Style>
  <Style ss:ID="s127">
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Calibri" ss:Size="13" ss:Color="#000000" ss:Bold="1"/>
   <Interior ss:Color="#C0C0C0" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="s128">
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Calibri" ss:Size="13" ss:Color="#000000" ss:Bold="1"/>
  </Style>
  <Style ss:ID="s129">
   <Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Calibri" ss:Size="13" ss:Color="#000000" ss:Bold="1"/>
  </Style>
  <Style ss:ID="s130">
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Calibri" ss:Size="13" ss:Color="#000000"/>
   <Interior ss:Color="#C0C0C0" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="s131">
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Calibri" ss:Size="13" ss:Color="#000000"/>
  </Style>
  <Style ss:ID="s132">
   <Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
   </Borders>
   <Font ss:FontName="Calibri" ss:Size="13" ss:Color="#000000"/>
  </Style>
 </Styles>
 <Worksheet ss:Name="Praga 25.06.2013 r.">
  <Table ss:ExpandedColumnCount="9" ss:ExpandedRowCount="13" x:FullColumns="1"
   x:FullRows="1" ss:DefaultColumnWidth="65" ss:DefaultRowHeight="15" ss:Border="1">
   <Column ss:Width="20"/>
   <Column ss:Width="110"/>
   <Column ss:Width="150"/>
   <Column ss:Width="63"/>
   <Column ss:Width="79" ss:Span="1"/>
   <Column ss:Index="7" ss:Width="96"/>
   <Column ss:StyleID="s62" ss:Width="86"/>
   <Column ss:AutoFitWidth="0" ss:Width="119"/>
   <Row ss:AutoFitHeight="0" ss:Height="26">
    <Cell ss:MergeAcross="8" ss:MergeDown="1" ss:StyleID="m706390908"><Data
      ss:Type="String">LISTA WYCIECZKI <%= FindWycieczkaByID(params[:id]).humanize %></Data></Cell>
   </Row>
   <Row ss:AutoFitHeight="0"/>
   <Row ss:AutoFitHeight="0" ss:Height="23" ss:StyleID="s100">
    <Cell ss:StyleID="s127"><Data ss:Type="String">ID</Data></Cell>
    <Cell ss:StyleID="s128"><Data ss:Type="String">Numer rezerwacji</Data></Cell>
    <Cell ss:StyleID="s128"><Data ss:Type="String">Przystanek</Data></Cell>
    <Cell ss:StyleID="s128"><Data ss:Type="String">Imie</Data></Cell>
    <Cell ss:StyleID="s128"><Data ss:Type="String">Nazwisko</Data></Cell>
    <Cell ss:StyleID="s128"><Data ss:Type="String">Telefon</Data></Cell>
    <Cell ss:StyleID="s128"><Data ss:Type="String">Data urodzenia</Data></Cell>
    <Cell ss:StyleID="s129"><Data ss:Type="String">Dodane przez</Data></Cell>
    <Cell ss:StyleID="s129"><Data ss:Type="String">Uwagi</Data></Cell>
   </Row>
   <% @i = 1 %>
   <% @rezerwacjas.each do |rezerwacja| %>
   <Row ss:AutoFitHeight="0" ss:Height="30">
    <Cell ss:StyleID="s130"><Data ss:Type="Number"><%= @i %></Data></Cell>
    <Cell ss:StyleID="s131"><Data ss:Type="String"><%= "#{User.find_by_id(rezerwacja.updated_by).username[0..2]}/#{rezerwacja.id}/#{Rezerwacja.find_by_id(rezerwacja.id).created_at.year}" %></Data></Cell>
    <Cell ss:StyleID="s131"><Data ss:Type="String"><%= rezerwacja.przystaneks.first.nazwa %></Data></Cell>
    <Cell ss:StyleID="s131"><Data ss:Type="String"><%= rezerwacja.imie %></Data></Cell>
    <Cell ss:StyleID="s131"><Data ss:Type="String"><%= rezerwacja.nazwisko %></Data></Cell>
    <Cell ss:StyleID="s131"><Data ss:Type="String"><%= rezerwacja.nrtelefonu %></Data></Cell>
    <Cell ss:StyleID="s131"><Data ss:Type="String"><%= rezerwacja.dataUrodzenia %></Data></Cell>

    <Cell ss:StyleID="s131"><Data ss:Type="String"><%= "#{User.find_by_id(rezerwacja.updated_by).username }" %></Data></Cell>
    <Cell ss:StyleID="s132"><Data ss:Type="String"><%= rezerwacja.uwagi %></Data></Cell>
   </Row>
   <% @i = @i + 1 %>
  <% end %>
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <PageSetup>
    <PageMargins x:Left="0.35000000000000009" x:Right="0.35000000000000009"
     x:Top="0.15000000000000011"/>
   </PageSetup>
   <Unsynced/>
   <Print>
    <ValidPrinterInfo/>
    <PaperSizeIndex>9</PaperSizeIndex>
    <Scale>67</Scale>
    <HorizontalResolution>-4</HorizontalResolution>
    <VerticalResolution>-4</VerticalResolution>
   </Print>
   <PageLayoutZoom>0</PageLayoutZoom>
   <Selected/>
   <Panes>
    <Pane>
     <Number>3</Number>
     <ActiveRow>9</ActiveRow>
     <ActiveCol>8</ActiveCol>
    </Pane>
   </Panes>
   <ProtectObjects>False</ProtectObjects>
   <ProtectScenarios>False</ProtectScenarios>
  </WorksheetOptions>
  <PageBreaks xmlns="urn:schemas-microsoft-com:office:excel">
   <ColBreaks>
    <ColBreak>
     <Column>9</Column>
    </ColBreak>
   </ColBreaks>
  </PageBreaks>
 </Worksheet>
</Workbook>

app/views/wycieczkas/new.html.erb
<%- model_class = Wycieczka -%>
<div class="span12">

<div class="page-header">
  <blockquote><p><big>Nowa wycieczka</big></p></blockquote>
</div>
</div>
<%= render :partial => 'form' %>
     

app/views/wycieczkas/show.html.erb
<%- model_class = Wycieczka -%>
<div class="span12">

<div class="page-header">
   <blockquote><p><big><p><%=t '.title', :default => model_class.model_name.human %></big></p></blockquote>
</div>
</div>
<div class="span12">

<dl class="dl-horizontal">
  
  <dt><strong>Miejsce:</strong></dt>
  <dd><%= @wycieczka.nazwa %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data) %>:</strong></dt>
  <dd><%= @wycieczka.data.strftime('%d-%m-%Y r.') %></dd>
</dl>
</div>
<div class="span12">

<div class="form-actions">
<%= link_to raw("<i class=\"icon-list\"></i> Lista"),
              wycieczkas_index_path, :class => 'btn btn-warning'  %>
  <%= link_to raw("<i class=\"icon-edit\"></i> Edytuj"),
              edit_wycieczka_path(@wycieczka), :class => 'btn btn-success' %>
  <%= link_to raw("<i class=\"icon-remove\"></i> Usuń"),
              wycieczka_path(@wycieczka),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Jesteś pewien?')) },
              :class => 'btn btn-danger' %>
</div>
</div>