config/routes.rb
BookingApp::Application.routes.draw do
  

  root :to => "rezerwacjas#index"
  resources :roles

  devise_for :users
  resources :users
  match 'przystanki' => "przystaneks#index", :as => 'przystaneks_index'
  match 'przystanek/nowy' => "przystaneks#new", :as => 'new_przystanek'
  match 'przystanek/create' => "przystaneks#create", :as => 'przystaneks'
  match 'przystanek/:id/edytuj' => "przystaneks#edit", :as => 'przystanek_edytuj'
  match 'przystanek/:id' => 'przystaneks#show', :as => 'przystanek_pokaz' 
  match 'przystanek/:id/usun' => 'przystaneks#destroy', :as => 'usun_przystanek'
  match 'wycieczki' => "wycieczkas#index", :as => 'wycieczkas_index'
  match 'wycieczka/nowa' => "wycieczkas#new", :as => 'new_wycieczka'
  match 'wycieczka/create' => "wycieczkas#create", :as => 'wycieczkas'
  match 'wycieczka/:id/lista' => "wycieczkas#lista", :as => 'lista_rezerwacji'
  match 'wycieczka/:id' => 'wycieczkas#show', :as => 'wycieczka_pokaz'
  match 'wycieczka/:id/edytuj' => 'wycieczkas#edit', :as => 'edit_wycieczka'
  match 'wycieczka/:id/usun' => 'wycieczkas#destroy', :as => 'usun_wycieczka'

  match 'rezerwacje' => "rezerwacjas#index", :as => 'rezerwacjas_index'
  match 'rezerwacja/nowa' => "rezerwacjas#new", :as => 'new_rezerwacja'
  match 'rezerwacja/create' => "rezerwacjas#create", :as => 'rezerwacjas'
  match 'rezerwacja/wycieczka/:id' => "rezerwacjas#new_const", :as => 'dodatkowa_rezerwacja'
  match 'rezerwacja/:id/nowa/osoba' => "rezerwacjas#new_person", :as => 'nowa_osoba'
  match 'rezerwacja/:id' => "rezerwacjas#show", :as => 'rezerwacja_pokaz'
  match 'rezerwacja/:id/edytuj' => "rezerwacjas#edit", :as => 'rezerwacja_edytuj'
  
  devise_scope :user do get "/wyloguj" => "devise/sessions#destroy" end
  devise_scope :user do get "/zaloguj" => "devise/sessions#new" ,:as => 'zaloguj' end
  match "/zarejestruj" => "users#new" ,:as => 'zarejestruj' 
  resources :wycieczkas

  resources :przystaneks

  resources :rezerwacjas

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookingApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script src="/assets/bootstrap-datepicker/locales/bootstrap-datepicker.pl.js?body=1" type="text/javascript"></script>
  <%= stylesheet_link_tag "bootstrap-datepicker.css" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "tabela-wyglad" %>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<%= root_url %>"><i class="icon-user"></i> Menadżer Wycieczek</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to raw("<i class=\"icon-time\"></i> Rezerwacje"), rezerwacjas_index_path %></li>
          <li><%= link_to raw("<i class=\"icon-road\"></i> Wycieczki"), wycieczkas_index_path %></li>
          <li><%= link_to raw("<i class=\"icon-flag\"></i> Przystanki"), przystaneks_index_path %></li>

        </ul>
        <ul class="nav pull-right">

          <% if current_user !=nil %>
                      <li class="pull-right"><%= link_to raw("<i class=\"icon-off\"></i> Wyloguj"), wyloguj_path, :class => "pull-right" %></li>

                    <% end %>          

        </ul>

      </div>

    </div>

  </div>
 
</div>



</div>
<% if current_user != nil  %>
  <blockquote class="pull-right">Witaj <%= current_user.username %></blockquote>
  <% else %>
 <blockquote class="pull-right"><%= link_to "Zaloguj", zaloguj_path %> | <%= link_to "Zarejestruj" , zarejestruj_path %></blockquote>
  <% end %>
 <div class="container">
    <div class="row">
   <%= yield %>
     
	
</div>
</div>
<br>
<br>
<br>


</body>
</html>